#测试环境配置
#jdbc 配置
spring:
  datasource:
    url: jdbc:mysql://test.pc.db:3306/test_pc_idmr?useUnicode=true&amp;characterEncoding=utf-8&allowMultiQueries=true
    username: bocom
    password: bocommysql
    driver-class-name: com.mysql.jdbc.Driver

#    系统访问名称以及端口号
server:
  port: 9001
  context-path: /JWJ

#    mybatis 配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.bocom.jwj.domain
  config-location: classpath:config/mybatis-config.xml

#    logback 配置
logging:
  config: classpath:config/logback-spring.xml